import mongoose, { Schema, Document, Model, Types } from 'mongoose';
import type { UserRole } from './User';

export type NotificationType =
  | 'assignment'
  | 'assessment'
  | 'message'
  | 'health'
  | 'registration'
  | 'submission'
  | 'system'
  | 'report'
  | 'audit_register'   // new student registered
  | 'audit_verify'     // student/teacher verified or activated
  | 'audit_create'     // teacher/admin account created by admin
  | 'audit_grade'      // assignment graded
  | 'audit_publish';   // assessment/content published

export interface INotification {
  userId: Types.ObjectId;
  role: UserRole;
  type: NotificationType;
  title: string;
  body: string;
  read: boolean;
  /**
   * isAudit = true means this notification was generated by a system action
   * (e.g., user registration, verification, grading). Admin can filter these
   * to replace the removed Audit Logs module.
   */
  isAudit: boolean;
  link?: string;
}

export interface INotificationDocument extends INotification, Document {}

const NotificationSchema = new Schema<INotificationDocument>(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User is required'],
    },
    role: {
      type: String,
      enum: ['admin', 'teacher', 'student'],
      required: [true, 'Role is required'],
    },
    type: {
      type: String,
      enum: [
        'assignment',
        'assessment',
        'message',
        'health',
        'registration',
        'submission',
        'system',
        'report',
        'audit_register',
        'audit_verify',
        'audit_create',
        'audit_grade',
        'audit_publish',
      ],
      required: true,
    },
    title: { type: String, required: true, trim: true },
    body: { type: String, required: true, trim: true },
    read: { type: Boolean, default: false },
    isAudit: { type: Boolean, default: false },
    link: { type: String, trim: true },
  },
  { timestamps: true }
);

NotificationSchema.index({ userId: 1, createdAt: -1 });
NotificationSchema.index({ userId: 1, read: 1 });
// Admin can query audit trail separately
NotificationSchema.index({ role: 1, isAudit: 1, createdAt: -1 });

export const NotificationModel: Model<INotificationDocument> =
  mongoose.models.Notification ||
  mongoose.model<INotificationDocument>('Notification', NotificationSchema);

export default NotificationModel;
